#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps' in
 * file 'hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'led', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_'.
 * The prefix is the slave descriptor.
 */
#define LED_COMPONENT_TYPE altera_avalon_pio
#define LED_COMPONENT_NAME led
#define LED_BASE 0x0
#define LED_SPAN 16
#define LED_END 0xf
#define LED_BIT_CLEARING_EDGE_REGISTER 0
#define LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_CAPTURE 0
#define LED_DATA_WIDTH 10
#define LED_DO_TEST_BENCH_WIRING 0
#define LED_DRIVEN_SIM_VALUE 0
#define LED_EDGE_TYPE NONE
#define LED_FREQ 50000000
#define LED_HAS_IN 0
#define LED_HAS_OUT 1
#define LED_HAS_TRI 0
#define LED_IRQ_TYPE NONE
#define LED_RESET_VALUE 0

/*
 * Macros for device 'hex03', class 'altera_avalon_pio'
 * The macros are prefixed with 'HEX03_'.
 * The prefix is the slave descriptor.
 */
#define HEX03_COMPONENT_TYPE altera_avalon_pio
#define HEX03_COMPONENT_NAME hex03
#define HEX03_BASE 0x10
#define HEX03_SPAN 16
#define HEX03_END 0x1f
#define HEX03_BIT_CLEARING_EDGE_REGISTER 0
#define HEX03_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX03_CAPTURE 0
#define HEX03_DATA_WIDTH 32
#define HEX03_DO_TEST_BENCH_WIRING 0
#define HEX03_DRIVEN_SIM_VALUE 0
#define HEX03_EDGE_TYPE NONE
#define HEX03_FREQ 50000000
#define HEX03_HAS_IN 0
#define HEX03_HAS_OUT 1
#define HEX03_HAS_TRI 0
#define HEX03_IRQ_TYPE NONE
#define HEX03_RESET_VALUE 0

/*
 * Macros for device 'hex45', class 'altera_avalon_pio'
 * The macros are prefixed with 'HEX45_'.
 * The prefix is the slave descriptor.
 */
#define HEX45_COMPONENT_TYPE altera_avalon_pio
#define HEX45_COMPONENT_NAME hex45
#define HEX45_BASE 0x20
#define HEX45_SPAN 16
#define HEX45_END 0x2f
#define HEX45_BIT_CLEARING_EDGE_REGISTER 0
#define HEX45_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX45_CAPTURE 0
#define HEX45_DATA_WIDTH 16
#define HEX45_DO_TEST_BENCH_WIRING 0
#define HEX45_DRIVEN_SIM_VALUE 0
#define HEX45_EDGE_TYPE NONE
#define HEX45_FREQ 50000000
#define HEX45_HAS_IN 0
#define HEX45_HAS_OUT 1
#define HEX45_HAS_TRI 0
#define HEX45_IRQ_TYPE NONE
#define HEX45_RESET_VALUE 0

/*
 * Macros for device 'button', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_COMPONENT_NAME button
#define BUTTON_BASE 0x30
#define BUTTON_SPAN 16
#define BUTTON_END 0x3f
#define BUTTON_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_CAPTURE 0
#define BUTTON_DATA_WIDTH 4
#define BUTTON_DO_TEST_BENCH_WIRING 0
#define BUTTON_DRIVEN_SIM_VALUE 0
#define BUTTON_EDGE_TYPE NONE
#define BUTTON_FREQ 50000000
#define BUTTON_HAS_IN 1
#define BUTTON_HAS_OUT 0
#define BUTTON_HAS_TRI 0
#define BUTTON_IRQ_TYPE NONE
#define BUTTON_RESET_VALUE 0

/*
 * Macros for device 'switches', class 'altera_avalon_pio'
 * The macros are prefixed with 'SWITCHES_'.
 * The prefix is the slave descriptor.
 */
#define SWITCHES_COMPONENT_TYPE altera_avalon_pio
#define SWITCHES_COMPONENT_NAME switches
#define SWITCHES_BASE 0x40
#define SWITCHES_SPAN 16
#define SWITCHES_END 0x4f
#define SWITCHES_BIT_CLEARING_EDGE_REGISTER 0
#define SWITCHES_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SWITCHES_CAPTURE 0
#define SWITCHES_DATA_WIDTH 10
#define SWITCHES_DO_TEST_BENCH_WIRING 0
#define SWITCHES_DRIVEN_SIM_VALUE 0
#define SWITCHES_EDGE_TYPE NONE
#define SWITCHES_FREQ 50000000
#define SWITCHES_HAS_IN 1
#define SWITCHES_HAS_OUT 0
#define SWITCHES_HAS_TRI 0
#define SWITCHES_IRQ_TYPE NONE
#define SWITCHES_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
