
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab2EM(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// HPS //////////
	inout 		          		HPS_CONV_USB_N,
	output		    [14:0]		HPS_DDR3_ADDR,
	output		     [2:0]		HPS_DDR3_BA,
	output		          		HPS_DDR3_CAS_N,
	output		          		HPS_DDR3_CKE,
	output		          		HPS_DDR3_CK_N,
	output		          		HPS_DDR3_CK_P,
	output		          		HPS_DDR3_CS_N,
	output		     [3:0]		HPS_DDR3_DM,
	inout 		    [31:0]		HPS_DDR3_DQ,
	inout 		     [3:0]		HPS_DDR3_DQS_N,
	inout 		     [3:0]		HPS_DDR3_DQS_P,
	output		          		HPS_DDR3_ODT,
	output		          		HPS_DDR3_RAS_N,
	output		          		HPS_DDR3_RESET_N,
	input 		          		HPS_DDR3_RZQ,
	output		          		HPS_DDR3_WE_N,
	output		          		HPS_ENET_GTX_CLK,
	inout 		          		HPS_ENET_INT_N,
	output		          		HPS_ENET_MDC,
	inout 		          		HPS_ENET_MDIO,
	input 		          		HPS_ENET_RX_CLK,
	input 		     [3:0]		HPS_ENET_RX_DATA,
	input 		          		HPS_ENET_RX_DV,
	output		     [3:0]		HPS_ENET_TX_DATA,
	output		          		HPS_ENET_TX_EN,
	inout 		     [3:0]		HPS_FLASH_DATA,
	output		          		HPS_FLASH_DCLK,
	output		          		HPS_FLASH_NCSO,
	inout 		          		HPS_GSENSOR_INT,
	inout 		          		HPS_I2C1_SCLK,
	inout 		          		HPS_I2C1_SDAT,
	inout 		          		HPS_I2C2_SCLK,
	inout 		          		HPS_I2C2_SDAT,
	inout 		          		HPS_I2C_CONTROL,
	inout 		          		HPS_KEY,
	inout 		          		HPS_LCM_BK,
	inout 		          		HPS_LCM_D_C,
	inout 		          		HPS_LCM_RST_N,
	output		          		HPS_LCM_SPIM_CLK,
	input 		          		HPS_LCM_SPIM_MISO,
	output		          		HPS_LCM_SPIM_MOSI,
	output		          		HPS_LCM_SPIM_SS,
	inout 		          		HPS_LED,
	inout 		          		HPS_LTC_GPIO,
	output		          		HPS_SD_CLK,
	inout 		          		HPS_SD_CMD,
	inout 		     [3:0]		HPS_SD_DATA,
	output		          		HPS_SPIM_CLK,
	input 		          		HPS_SPIM_MISO,
	output		          		HPS_SPIM_MOSI,
	output		          		HPS_SPIM_SS,
	input 		          		HPS_UART_RX,
	output		          		HPS_UART_TX,
	input 		          		HPS_USB_CLKOUT,
	inout 		     [7:0]		HPS_USB_DATA,
	input 		          		HPS_USB_DIR,
	input 		          		HPS_USB_NXT,
	output		          		HPS_USB_STP
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

    hps u0 (
	 
	 /*
			 .clk_clk(CLOCK_50),                               // Input clock
    .memory_mem_a(HPS_DDR3_ADDR),                     // DDR3 Address
    .memory_mem_ba(HPS_DDR3_BA),                      // DDR3 Bank Address
    .memory_mem_ck(HPS_DDR3_CK_P),                    // DDR3 Clock Positive
    .memory_mem_ck_n(HPS_DDR3_CK_N),                  // DDR3 Clock Negative
    .memory_mem_cke(HPS_DDR3_CKE),                    // DDR3 Clock Enable
    .memory_mem_cs_n(HPS_DDR3_CS_N),                  // DDR3 Chip Select
    .memory_mem_ras_n(HPS_DDR3_RAS_N),                // DDR3 Row Address Select
    .memory_mem_cas_n(HPS_DDR3_CAS_N),                // DDR3 Column Address Select
    .memory_mem_we_n(HPS_DDR3_WE_N),                  // DDR3 Write Enable
    .memory_mem_reset_n(HPS_DDR3_RESET_N),            // DDR3 Reset
    .memory_mem_dq(HPS_DDR3_DQ),                      // DDR3 Data
    .memory_mem_dqs(HPS_DDR3_DQS_P),                  // DDR3 Data Strobe Positive
    .memory_mem_dqs_n(HPS_DDR3_DQS_N),                // DDR3 Data Strobe Negative
    .memory_mem_odt(HPS_DDR3_ODT),                    // DDR3 On-Die Termination
    .memory_mem_dm(HPS_DDR3_DM),                      // DDR3 Data Mask
    .memory_oct_rzqin(HPS_DDR3_RZQ),                  // DDR3 Impedance Calibration
	 .hps_io_hps_io_gpio_inst_GPIO35(HPS_ENET_INT_N),
    .hps_io_hps_io_emac1_inst_TX_CLK(HPS_ENET_GTX_CLK),
    .hps_io_hps_io_emac1_inst_TXD0(HPS_ENET_TX_DATA[0]),
    .hps_io_hps_io_emac1_inst_TXD1(HPS_ENET_TX_DATA[1]),
    .hps_io_hps_io_emac1_inst_TXD2(HPS_ENET_TX_DATA[2]),
    .hps_io_hps_io_emac1_inst_TXD3(HPS_ENET_TX_DATA[3]),
    .hps_io_hps_io_emac1_inst_RXD0(HPS_ENET_RX_DATA[0]),
    .hps_io_hps_io_emac1_inst_MDIO(HPS_ENET_MDIO),
    .hps_io_hps_io_emac1_inst_MDC(HPS_ENET_MDC),
    .hps_io_hps_io_emac1_inst_RX_CTL(HPS_ENET_RX_DV),
    .hps_io_hps_io_emac1_inst_TX_CTL(HPS_ENET_TX_EN),
    .hps_io_hps_io_emac1_inst_RX_CLK(HPS_ENET_RX_CLK),
    .hps_io_hps_io_emac1_inst_RXD1(HPS_ENET_RX_DATA[1]),
    .hps_io_hps_io_emac1_inst_RXD2(HPS_ENET_RX_DATA[2]),
    .hps_io_hps_io_emac1_inst_RXD3(HPS_ENET_RX_DATA[3]),
	 .hps_io_hps_io_sdio_inst_CMD (HPS_SD_CMD),         
    .hps_io_hps_io_sdio_inst_D0 (HPS_SD_DATA[0]),      
    .hps_io_hps_io_sdio_inst_D1 (HPS_SD_DATA[1]),      
    .hps_io_hps_io_sdio_inst_CLK(HPS_SD_CLK),          
    .hps_io_hps_io_sdio_inst_D2 (HPS_SD_DATA[2]),      
    .hps_io_hps_io_sdio_inst_D3(HPS_SD_DATA[3]),    
    .hps_io_hps_io_usb1_inst_D0(HPS_USB_DATA[0]),
    .hps_io_hps_io_usb1_inst_D1(HPS_USB_DATA[1]),
    .hps_io_hps_io_usb1_inst_D2(HPS_USB_DATA[2]),
    .hps_io_hps_io_usb1_inst_D3(HPS_USB_DATA[3]),
    .hps_io_hps_io_usb1_inst_D4(HPS_USB_DATA[4]),
    .hps_io_hps_io_usb1_inst_D5(HPS_USB_DATA[5]),
    .hps_io_hps_io_usb1_inst_D6(HPS_USB_DATA[6]),
    .hps_io_hps_io_usb1_inst_D7(HPS_USB_DATA[7]),
    .hps_io_hps_io_usb1_inst_CLK(HPS_USB_CLKOUT),
    .hps_io_hps_io_usb1_inst_STP(HPS_USB_STP),
    .hps_io_hps_io_usb1_inst_DIR(HPS_USB_DIR),
    .hps_io_hps_io_usb1_inst_NXT(HPS_USB_NXT),
    .hps_io_hps_io_uart0_inst_RX(HPS_UART_RX),
    .hps_io_hps_io_uart0_inst_TX(HPS_UART_TX),
    .led_external_connection_export(LEDR),            // Connect LEDs to LEDR
    .button_external_connection_export (KEY[0]), // button_external_connection.export
        .hex_external_connection_export    (HEX0)  
	 
	 */
        .clk_clk(CLOCK_50),                               // Input clock
        .memory_mem_a(HPS_DDR3_ADDR),                     // DDR3 Address
        .memory_mem_ba(HPS_DDR3_BA),                      // DDR3 Bank Address
        .memory_mem_ck(HPS_DDR3_CK_P),                    // DDR3 Clock Positive
        .memory_mem_ck_n(HPS_DDR3_CK_N),                  // DDR3 Clock Negative
        .memory_mem_cke(HPS_DDR3_CKE),                    // DDR3 Clock Enable
        .memory_mem_cs_n(HPS_DDR3_CS_N),                  // DDR3 Chip Select
        .memory_mem_ras_n(HPS_DDR3_RAS_N),                // DDR3 Row Address Select
        .memory_mem_cas_n(HPS_DDR3_CAS_N),                // DDR3 Column Address Select
        .memory_mem_we_n(HPS_DDR3_WE_N),                  // DDR3 Write Enable
        .memory_mem_reset_n(HPS_DDR3_RESET_N),            // DDR3 Reset
        .memory_mem_dq(HPS_DDR3_DQ),                      // DDR3 Data
        .memory_mem_dqs(HPS_DDR3_DQS_P),                  // DDR3 Data Strobe Positive
        .memory_mem_dqs_n(HPS_DDR3_DQS_N),                // DDR3 Data Strobe Negative
        .memory_mem_odt(HPS_DDR3_ODT),                    // DDR3 On-Die Termination
        .memory_mem_dm(HPS_DDR3_DM),                      // DDR3 Data Mask
        .memory_oct_rzqin(HPS_DDR3_RZQ),                  // DDR3 Impedance Calibration
	     .hps_io_hps_io_gpio_inst_GPIO35(HPS_ENET_INT_N),
        .hps_io_hps_io_emac1_inst_TX_CLK(HPS_ENET_GTX_CLK),
        .hps_io_hps_io_emac1_inst_TXD0(HPS_ENET_TX_DATA[0]),
        .hps_io_hps_io_emac1_inst_TXD1(HPS_ENET_TX_DATA[1]),
        .hps_io_hps_io_emac1_inst_TXD2(HPS_ENET_TX_DATA[2]),
        .hps_io_hps_io_emac1_inst_TXD3(HPS_ENET_TX_DATA[3]),
        .hps_io_hps_io_emac1_inst_RXD0(HPS_ENET_RX_DATA[0]),
        .hps_io_hps_io_emac1_inst_MDIO(HPS_ENET_MDIO),
        .hps_io_hps_io_emac1_inst_MDC(HPS_ENET_MDC),
        .hps_io_hps_io_emac1_inst_RX_CTL(HPS_ENET_RX_DV),
        .hps_io_hps_io_emac1_inst_TX_CTL(HPS_ENET_TX_EN),
        .hps_io_hps_io_emac1_inst_RX_CLK(HPS_ENET_RX_CLK),
        .hps_io_hps_io_emac1_inst_RXD1(HPS_ENET_RX_DATA[1]),
        .hps_io_hps_io_emac1_inst_RXD2(HPS_ENET_RX_DATA[2]),
        .hps_io_hps_io_emac1_inst_RXD3(HPS_ENET_RX_DATA[3]),
	     .hps_io_hps_io_sdio_inst_CMD (HPS_SD_CMD),         
        .hps_io_hps_io_sdio_inst_D0 (HPS_SD_DATA[0]),      
        .hps_io_hps_io_sdio_inst_D1 (HPS_SD_DATA[1]),      
        .hps_io_hps_io_sdio_inst_CLK(HPS_SD_CLK),          
        .hps_io_hps_io_sdio_inst_D2 (HPS_SD_DATA[2]),      
        .hps_io_hps_io_sdio_inst_D3(HPS_SD_DATA[3]),    
        .hps_io_hps_io_usb1_inst_D0(HPS_USB_DATA[0]),
        .hps_io_hps_io_usb1_inst_D1(HPS_USB_DATA[1]),
        .hps_io_hps_io_usb1_inst_D2(HPS_USB_DATA[2]),
        .hps_io_hps_io_usb1_inst_D3(HPS_USB_DATA[3]),
        .hps_io_hps_io_usb1_inst_D4(HPS_USB_DATA[4]),
        .hps_io_hps_io_usb1_inst_D5(HPS_USB_DATA[5]),
        .hps_io_hps_io_usb1_inst_D6(HPS_USB_DATA[6]),
        .hps_io_hps_io_usb1_inst_D7(HPS_USB_DATA[7]),
        .hps_io_hps_io_usb1_inst_CLK(HPS_USB_CLKOUT),
        .hps_io_hps_io_usb1_inst_STP(HPS_USB_STP),
        .hps_io_hps_io_usb1_inst_DIR(HPS_USB_DIR),
        .hps_io_hps_io_usb1_inst_NXT(HPS_USB_NXT),
        .hps_io_hps_io_uart0_inst_RX(HPS_UART_RX),
        .hps_io_hps_io_uart0_inst_TX(HPS_UART_TX),
        .led_external_connection_export(LEDR),            // Connect LEDs to LEDR
        .button_external_connection_export (KEY), // button_external_connection.export
        .hex03_external_connection_export  ({1'b0,HEX3,1'b0,HEX2,1'b0,HEX1,1'b0,HEX0}),  //  hex03_external_connection.export
        .hex45_external_connection_export  ({1'b0,HEX5,1'b0,HEX4}),   //  hex45_external_connection.export
		  .switches_external_connection_export (SW)
    );



endmodule
